# Generated by Django 4.2.9 on 2024-03-07 14:11

from django.db import migrations, models
import django.utils.crypto


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_invitetoteam_email_alter_invitetoteam_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoteam',
            name='email',
            field=models.EmailField(default=django.utils.crypto.get_random_string, max_length=100),
        ),
        migrations.AlterField(
            model_name='invitetoteam',
            name='token',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
