# Generated by Django 4.2.9 on 2024-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_admin',
            field=models.BooleanField(default=False),
        ),
    ]
